server:
  port: 3000
version: '3'
spring :
  datasource :
    url : jdbc:postgresql://localhost:5432/WebStore
    username: postgres
    password : roei
  jpa :
    database-platform : org.hibernate.dialect.PostgreSQLDialect
